# nn parameters
INPUT_NUM = 2
OUTPUT_NUM = 1

NORMAL_NUM_UPPER_LIMIT = 5
NORMAL_NUM_LOWER_LIMIT = 2

MODULATION_NUM_UPPER_LIMIT = 2
MODULATION_NUM_LOWER_LIMIT = 2

NEURON_NUM_UPPER_LIMIT = 5

CONNECTION_NUM_UPPER_LIMIT = 10
CONNECTION_NUM_LOWER_LIMIT = 1

WEIGHT_UPPER_LIMIT = 1.0
WEIGHT_LOWER_LIMIT = -1.0

BIAS_UPPER_LIMIT = 1.0
BIAS_LOWER_LIMIT = -1.0

EVOLUTION_PARAM_UPPER_LIMIT = 1.0
EVOLUTION_PARAM_LOWER_LIMIT = -1.0

EPSIRON_LOWER_LIMIT = 0.01
EPSIRON_UPPER_LIMIT = 1.0
